### ISSUE TITLE
RFC: Future of sentry-rust

### ISSUE THREAD

**Issue by Swatinem** [getsentry/sentry-rust#190]
Hey!

The `sentry-rust` SDK needs some love. I will take care of it in the weeks and months ahead. Here are my plans on what I would like to achieve.

## TLDR:

* Ship a tiny *stable* `sentry-core`, with minimal dependencies.
* Create integration / transport traits that hook into `sentry-core`.
* Ship integrations for popular crates/frameworks independently from `sentry-core`.
* Bundle a default set of useful and popular integrations, and a transport as `sentry`.

## Slim *stable* `sentry-core`

We would like to extract the core Sentry API into a small crate called `sentry-core`.
This will be focused around the existing concepts of `Hub`s and `Scope`s, and their event
capturing methods.

This should be useful for crates that would like instrument code with sentry, without actually
integrating with all of sentry.

It is also the primary interaction point for Integrations and Transports which are
explained in more detail below.

We aim to ship a stable `1.0` release of `sentry-core` as soon as possible, to encourage
external integrations. Additionally, `sentry-core` should have as few external dependencies
as possible, ideally only `sentry-types`.

## Integrations

Integrations can interact with `sentry-core` in the following two ways.
They can either *create* new data to be fed to sentry, such as `Scope` data, `Breadcrumb`s
or `Event`s. Or they can *process* `Event`s as they flow through the sentry pipeline.

Draft:

```rust
trait Integration: Send + Sync + 'static {
  /// The name this integration should be identified by.
  /// TODO: do we want this, for bookkeeping reasons, or rather encourage
  /// Integrations to advertise themselves in the scope?
  fn name(&self) -> &str;
  
  /// The setup hook will be called once, when the sentry client is
  /// initialized with this integration.
  /// The integration can use this hook to both add information to
  /// the sentry `Scope`, as well as to register with an external
  /// event source.
  fn setup(&self) {}
    
  /// An integration can process, or even completely drop an `Event`.
  /// Examples include adding or processing a backtrace, obfuscate
  /// some personal information, or add additional information.
  /// TODO: should this rather return a `Result<Option, …>`?
  fn process_event(&self, event: Event<'static>) -> Option<Event<'static>> {
    Some(event)
  }
}
```

## Transports

A Transport is the part that actually uploads Envelopes to the sentry server.
Depending on the usecase, sentry users might actually want to handle sending
via their own HTTP infrastructure.

Draft:

```rust
trait Transport: Send + Sync + 'static {
  /// Sends an Envelope.
  fn send_envelope(&self, envelope: Envelope);

  /// Flush the current send queue if there is one.
  ///
  /// The default implementation does nothing.  If the queue was successfully
  /// shut down, the return value should be `true` or `false` if events were
  /// left in it.
  fn flush(&self, timeout: Duration) -> bool {
    let _timeout = timeout;
    true
  }

  /// Shuts down the Transport
  fn shutdown(&self, timeout: Duration) -> bool {
    self.flush(timeout)
  }
}
```

## Sentry

The main `sentry` crate will re-export `sentry-core`, and bundle it
with a set of default integrations, and a default HTTP transport.

Ideally, `sentry` is a *very small* shim on top of `sentry-core`.

## Open Questions

- Do we want to have feature flags on `sentry`, or rather instruct users
  to build on `sentry-core` if they do not want to build the default integrations?
- How should we expose / hook into sentry-internal logging?

## Breaking Changes

I would like to avoid breaking changes as much as possible, but will do them if necessary.
Also, this could be an opportunity to clean up all the deprecated functions.

## Implementation Plan

* [x] Create a new workspace with `sentry` and empty `sentry-core`.
* [x] Start moving core functionality from `sentry` to `sentry-core`.
* [x] Define the `Integration` trait, and start moving integrations over.
* [x] Maybe change `Transport` from `Event` to newly defined `Envelope`.
* [ ] If we are happy with `sentry-core`, cut a `1.0` release ;-)

**Comment by amircodota** [comment]
@Swatinem one very important issue for us is [this one](https://github.com/getsentry/sentry-rust/issues/164).

Without it, we cannot use sentry-rust, because the stack traces have no meaning.

Would really appreciate if as part of your work, you can address this too.

**Comment by nickbp** [comment]
I ended up hitting issues with trying to cross-build a binary that includes sentry-rust. The specific error was that the build environment didn't have openssl installed. This error was surprising, until I saw the dependency tree of everything that sentry was pulling in (via `cargo tree`):
```
├── sentry v0.18.0
│   ├── backtrace v0.3.44
│   │   ├── backtrace-sys v0.1.32
│   │   │   └── libc v0.2.66 (*)
│   │   │   [build-dependencies]
│   │   │   └── cc v1.0.50 (*)
│   │   ├── cfg-if v0.1.10 (*)
│   │   ├── libc v0.2.66 (*)
│   │   └── rustc-demangle v0.1.16
│   ├── failure v0.1.6
│   │   ├── backtrace v0.3.44 (*)
│   │   └── failure_derive v0.1.6
│   │       ├── proc-macro2 v1.0.8 (*)
│   │       ├── quote v1.0.2 (*)
│   │       ├── syn v1.0.14 (*)
│   │       └── synstructure v0.12.3
│   │           ├── proc-macro2 v1.0.8 (*)
│   │           ├── quote v1.0.2 (*)
│   │           ├── syn v1.0.14 (*)
│   │           └── unicode-xid v0.2.0 (*)
│   ├── hostname v0.3.0
│   │   ├── libc v0.2.66 (*)
│   │   └── match_cfg v0.1.0
│   ├── httpdate v0.3.2
│   ├── im v14.2.0
│   │   ├── bitmaps v2.0.0
│   │   │   └── typenum v1.11.2
│   │   ├── rand_core v0.5.1 (*)
│   │   ├── rand_xoshiro v0.4.0
│   │   │   └── rand_core v0.5.1 (*)
│   │   ├── sized-chunks v0.5.1
│   │   │   ├── bitmaps v2.0.0 (*)
│   │   │   └── typenum v1.11.2 (*)
│   │   └── typenum v1.11.2 (*)
│   │   [build-dependencies]
│   │   └── version_check v0.9.1
│   ├── lazy_static v1.4.0 (*)
│   ├── libc v0.2.66 (*)
│   ├── rand v0.7.3 (*)
│   ├── regex v1.3.4
│   │   ├── aho-corasick v0.7.8
│   │   │   └── memchr v2.3.0 (*)
│   │   ├── memchr v2.3.0 (*)
│   │   ├── regex-syntax v0.6.14
│   │   └── thread_local v1.0.1
│   │       └── lazy_static v1.4.0 (*)
│   ├── reqwest v0.10.2
│   │   ├── base64 v0.11.0
│   │   ├── bytes v0.5.4 (*)
│   │   ├── encoding_rs v0.8.22
│   │   │   └── cfg-if v0.1.10 (*)
│   │   ├── futures-core v0.3.1 (*)
│   │   ├── futures-util v0.3.1 (*)
│   │   ├── http v0.2.0 (*)
│   │   ├── http-body v0.3.1 (*)
│   │   ├── hyper v0.13.2 (*)
│   │   ├── hyper-tls v0.4.1
│   │   │   ├── bytes v0.5.4 (*)
│   │   │   ├── hyper v0.13.2 (*)
│   │   │   ├── native-tls v0.2.3
│   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   ├── openssl v0.10.28
│   │   │   │   │   ├── bitflags v1.2.1 (*)
│   │   │   │   │   ├── cfg-if v0.1.10 (*)
│   │   │   │   │   ├── foreign-types v0.3.2
│   │   │   │   │   │   └── foreign-types-shared v0.1.1
│   │   │   │   │   ├── lazy_static v1.4.0 (*)
│   │   │   │   │   ├── libc v0.2.66 (*)
│   │   │   │   │   └── openssl-sys v0.9.54
│   │   │   │   │       └── libc v0.2.66 (*)
│   │   │   │   │       [build-dependencies]
│   │   │   │   │       ├── autocfg v1.0.0 (*)
│   │   │   │   │       ├── cc v1.0.50 (*)
│   │   │   │   │       └── pkg-config v0.3.17
│   │   │   │   ├── openssl-probe v0.1.2 (*)
│   │   │   │   └── openssl-sys v0.9.54 (*)
│   │   │   ├── tokio v0.2.11 (*)
│   │   │   └── tokio-tls v0.3.0
│   │   │       ├── native-tls v0.2.3 (*)
│   │   │       └── tokio v0.2.11 (*)
│   │   ├── lazy_static v1.4.0 (*)
│   │   ├── log v0.4.8 (*)
│   │   ├── mime v0.3.16
│   │   ├── mime_guess v2.0.1
│   │   │   ├── mime v0.3.16 (*)
│   │   │   └── unicase v2.6.0
│   │   │       [build-dependencies]
│   │   │       └── version_check v0.9.1 (*)
│   │   │   [build-dependencies]
│   │   │   └── unicase v2.6.0 (*)
│   │   ├── native-tls v0.2.3 (*)
│   │   ├── percent-encoding v2.1.0
│   │   ├── pin-project-lite v0.1.4 (*)
│   │   ├── serde v1.0.104 (*)
│   │   ├── serde_json v1.0.48
│   │   │   ├── itoa v0.4.5 (*)
│   │   │   ├── ryu v1.0.2
│   │   │   └── serde v1.0.104 (*)
│   │   ├── serde_urlencoded v0.6.1
│   │   │   ├── dtoa v0.4.5
│   │   │   ├── itoa v0.4.5 (*)
│   │   │   ├── serde v1.0.104 (*)
│   │   │   └── url v2.1.1
│   │   │       ├── idna v0.2.0
│   │   │       │   ├── matches v0.1.8
│   │   │       │   ├── unicode-bidi v0.3.4
│   │   │       │   │   └── matches v0.1.8 (*)
│   │   │       │   └── unicode-normalization v0.1.12
│   │   │       │       └── smallvec v1.2.0 (*)
│   │   │       ├── matches v0.1.8 (*)
│   │   │       ├── percent-encoding v2.1.0 (*)
│   │   │       └── serde v1.0.104 (*)
│   │   ├── time v0.1.42 (*)
│   │   ├── tokio v0.2.11 (*)
│   │   ├── tokio-tls v0.3.0 (*)
│   │   └── url v2.1.1 (*)
│   ├── sentry-types v0.14.1
│   │   ├── chrono v0.4.10 (*)
│   │   ├── debugid v0.7.0
│   │   │   ├── lazy_static v1.4.0 (*)
│   │   │   ├── regex v1.3.4 (*)
│   │   │   ├── serde v1.0.104 (*)
│   │   │   └── uuid v0.8.1
│   │   │       ├── rand v0.7.3 (*)
│   │   │       └── serde v1.0.104 (*)
│   │   ├── failure v0.1.6 (*)
│   │   ├── serde v1.0.104 (*)
│   │   ├── serde_json v1.0.48 (*)
│   │   ├── url v2.1.1 (*)
│   │   └── uuid v0.8.1 (*)
│   ├── uname v0.1.1
│   │   └── libc v0.2.66 (*)
│   └── url v2.1.1 (*)
```
Note the `sentry -> reqwest -> hyper-tls -> native-tls -> openssl` chain.

Somewhat annoying since the parent binary is already using `rustls` specifically to avoid these cross-build issues. Ended up just removing `sentry` since cross-builds are required.

As another point of comparison, removing `sentry-rust` brought stripped release builds of the binary from X to Y, and reduced cold-start compilation time on my laptop from X to Y.

**Comment by Swatinem** [comment]
There is a feature flag to turn the transports off, so you can roll your own!
Also, the tls backend is also available as a feature flag.

Might have been good to open a separate issue, as this has nothing to do with me trying to rearchitect the library.

**Comment by nickbp** [comment]
The first item on your list was reducing bloat in the library, so it sounded like a comment describing a specific case of bloat in the library as an example of what could be improved and justification for this refactoring work would be relevant.

If I see further issues (such as that the [docs incorrectly claim rusttls is the default](https://getsentry.github.io/sentry-rust/sentry/#features) when the default reqwest transport is used, contrary to what I had seen per above) then I'll file them separately, but given it sounds like everything's about to be restructured there isn't much point in trying to optimize against the current library.

**Comment by shaleh** [comment]
My thoughts.

Support the simplest use cases:
 - call something like capture_messsage() to send a Sentry message.
 - a panic handler in case of program failure

After that, middleware for various popular web toolkits. That should handle many people's wants.

The simple case can be 'sentry' package. Then people can use sentry-<my_favorite_webhandler> crates to add in the extra bits.

Your 'sentry-core' can live under all of this.

**Comment by repi** [comment]
We (Embark) would strongly prefer a _sans IO_ approach for this crate as its core. 

Have a `sentry-core` or similar with the Sentry specific types and message creation support, but don't have it depend on higher-level crates that determine system information and esp. do not do the actual network IO in it itself.

Then one can have a higher-level crate, with batteries included, that has additional integrations and implements automatic network IO support.

**Comment by jan-auer** [comment]
The current architecture we're moving to is:

- `sentry-core` with all types, traits and basic capture methods
- `sentry-*` with integrations, transports, third-party-specifics
- `sentry` with feature-flagged re-export of the most commonly used integrations for convenience

This should facilitate the three main use cases we've encountered so far:
1. A standard user just depends on `sentry` and sets a few feature flags
2. Extended use cases pull in additional `sentry-*` crates
3. A library or subcrate can just depend on `sentry-core` to add instrumentation, without pulling in the entire Sentry client and its transports.

**Comment by Jake-Shadle** [comment]
Are there any plans to provide a Rust crate that wraps your Native SDK that would be compatible with the proposed sentry-core crate?

I ask because we are at the point where we need to use the Native SDK so that we can report crashes, not just panics, but due to how the native SDK is built we'd have to invest time in actually wrapping it properly and passing information back to rust to eg not have an openssl dependency etc, and it seems like that kind of work would tie into this proposed structure so that rust codebases could easily use the native SDK if they wanted to.

**Comment by jan-auer** [comment]
We don't have any plans for wrapping the Rust SDK, but we do have plans for eventually writing a crash reporter in Rust that eventually makes it into the Native SDK. This crash reporter would be an integration like any other. There's still quite a road ahead for this, though.

Depending on platform support and the expected feature set, it may not be too hard to wrap the Native SDK today. The challenges lie mostly in synchronizing scope info, like the user and release. You can already build the Native SDK without a transport, which removes the OpenSSL dependency.

**Comment by Jake-Shadle** [comment]
Ok, thanks for the info!

**Comment by Swatinem** [comment]
I was CCd recently on a mail that said that apparently a 3rd party is working on something like this.

**Comment by Jake-Shadle** [comment]
That's good to know, we'd like to contribute to that if it's public somewhere, as there is little point in everyone rolling their own.

**Comment by daxpedda** [comment]
> I was CCd recently on a mail that said that apparently a 3rd party is working on something like this.

I'm assuming that third party is me, I hope to make it public by tomorrow.

**Comment by daxpedda** [comment]
I made my preliminary work public here: https://github.com/daxpedda/sentry-native
It still needs a lot of polishing, still if anybody has feedback feel free to drop it there.

**Comment by jan-auer** [comment]
Thank you so much, @daxpedda. How would you feel if we open a new issue either in this repo or in yours to talk about your approach and integrating this into the SDK? 

There was also a question about naming community contributed packages for the Rust SDK. I would suggest to give them some additional marker like `sentry-contrib-*`, just so that they don't clash with officially maintained packages. That would also help to set expectations for how much we can help with such integrations.

**Comment by daxpedda** [comment]
> How would you feel if we open a new issue either in this repo or in yours to talk about your approach and integrating this into the SDK?

I would feel delighted! Either repo is fine with me, we can also split up the discussion, make an issue on my repo about the approach and an issue on this repo for integrating, I leave that up to you.
> There was also a question about naming community contributed packages for the Rust SDK. I would suggest to give them some additional marker like `sentry-contrib-*`, just so that they don't clash with officially maintained packages. That would also help to set expectations for how much we can help with such integrations.

@mitsuhiko, I blame YOU for this blunder 😄.
I've already reserved `sentry-native` and `sentry-native-sys` on crates.io, just hit me up if you want ownership of them.
In any case I will rename them.

**Comment by daxpedda** [comment]
I published a pre-release on crates.io: https://crates.io/crates/sentry-contrib-native/0.1.0-alpha-2.

Looking for feedback.

**Comment by daxpedda** [comment]
0.1.0 is out now: https://crates.io/crates/sentry-contrib-native-sys.
We could start talking about integration now.

I would still love some feedback and some more pair of eyes on the code.
Thank you @Jake-Shadle and @Swatinem for the work so far :heart:!

**Comment by Swatinem** [comment]
checking this off, as we are now in a much better place then some time ago ;-)
